### ISSUE TITLE
Fetcha filmer från API

### ISSUE THREAD

**Issue by JoinetBasteed** [JoinetBasteed/SUTflix#4]
Hämta följande:
-Poster
-Titel
-Utgivningsår
-Genre
-Rating

Hittat 2 möjliga apier:
https://developers.themoviedb.org/3/getting-started/introduction
http://www.omdbapi.com

**Comment by Carpenteri1** [comment]
Apin http://www.omdbapi.com är implementerad och kan nu hämta: 
-Poster
-Titel
-Utgivningsår
-Genre
-Rating
