### ISSUE TITLE
Skriva WebAPI funktion

### ISSUE THREAD

**Issue by JoinetBasteed** [JoinetBasteed/SUTflix#8]
Vi måste ha minst 4 api funktioner, min tanke är att vi tar hem filmer med omdb apin, lägger till dem i en databas och bygger sedan en egen api

**Comment by Carpenteri1** [comment]
Addat så det sparas i databasen, men kan tyvärr inte läsa från databasen i nuläget

**Comment by Carpenteri1** [comment]
Done
